### PR TITLE
Support netstandard2.0

### LINKED ISSUE #392: OpenCVSharp.Extensions not available in .net core 2.0 app
Nuget Package: Opencvsharp3.AnyCpu
OpenCVSharp.Extensions not available in .net core 2.0 app 

# Environment

Linux/Windows .net core 2.0 console application

https://github.com/shimat/opencvsharp/blob/master/src/OpenCvSharp.Extensions/OpenCvSharp.Extensions.csproj

No build target for netstandard libraries. Im guessing this means that the extensions library is only avaliable for net40;net46 based applications.

### PR DESCRIPTION
**Pull request by shimat**
- Remove `netstandard1.6` and `netcoreapp1.0` support
- OpenCvSharp.Extensions is available on netstandard2.0
  - Close #392

### CODE REVIEW

**Comment by turowicz** [comment]
@shimat I've installed latest nuget package and can reference all OpenCVSharp libs apart from the .Extensions

Am I the only one with this problem?

**Comment by ricardomga** [comment]
I also have this problem

**Comment by ricardomga** [comment]
@turowicz did you manage to get the extension working?

**Comment by bozkurtfurkan** [comment]
@shimat I also have this problem.

**Comment by shimat** [comment]
I am sorry for the late reply. I will fix it by #566.

**Pull request merged**
