### PR TITLE
[PR] The proj files have been updated to enable SourceLink

### PR DESCRIPTION
**Pull request by JTOne123**
CSProj files have been updated to enable SourceLink in your nuget
---

*[This pull request was created with an automated workflow]*

I noticed that your repository and Nuget package are important for our .NET community, but you still haven't enabled SourceLink.

**We have to take 2 steps:**
1) Please approve this pull request and make .NET a better place for .NET developers and their debugging.
2) **Then just upload the .snupkg file** to https://www.nuget.org/ (now you can find the snupkg file along with the .nuget file)

You can find more information about SourceLine at the following links  
https://github.com/dotnet/sourcelink
https://www.hanselman.com/blog/ExploringNETCoresSourceLinkSteppingIntoTheSourceCodeOfNuGetPackagesYouDontOwn.aspx

If you are interesting about this automated workflow and how it works  
https://github.com/JTOne123/GitHubMassUpdater

*If you notice any flaws, please comment and I will try to make fixes manually*

### CODE REVIEW

**Comment by shimat** [comment]
Thanks for the pull request. How can I create a .snupkg file?
I'm currently using the `nuget.exe pack` command and I guess that way SourceLink won't work. Do I need to use `dotnet pack` instead?
https://github.com/shimat/opencvsharp/blob/master/appveyor.yml#L105

My `nuget pack` command above already outputs snupkg, what is the difference between that and SourceLink?

**Comment by shimat** [comment]
I think it would be easier to add the following line to my nuspec.
```xml
<repository type="git" url="https://github.com/shimat/opencvsharp.git" commit="xxxxx" />
```

https://www.hanselman.com/blog/ExploringNETCoresSourceLinkSteppingIntoTheSourceCodeOfNuGetPackagesYouDontOwn.aspx

**Comment by JTOne123** [comment]
yes, you can

about nuget pack
https://www.meziantou.net/how-to-debug-nuget-packages-using-sourcelink.htm

**Comment by shimat** [comment]
thank you for your contribution :+1:

**Pull request merged**
