### PR TITLE
Keep native DLLs under packages and reference them as links using an msbuild include

### PR DESCRIPTION
**Pull request by marklam**
More serious change than my previous PRs...

Rather than copy the native dlls into every project in the solution (and its source control), this change would keep them under the package folder and add them to the msbuild process via a .props file that NuGet will automatically add as an 'include' in the .*proj file.
The dlls don't appear in Solution explorer, but they are copied to the output folder during the build (tested in Visual Studio 2013 and TeamCity CI build).
After upgrading to this version of the NuGet package, the 'dll' trees (under the project in Solution Explorer and the filesystem) can be deleted.

I have also updated the 'without dlls' package specification - though I don't know if this makes that package less necessary - and added the Extern dll to that package since it's not part of the opencv binaries. ( Issue #98 )

### CODE REVIEW

**Comment by shimat** [comment]
Great PR!  Thank you so much!! :+1:

**Comment by marklam** [comment]
Thanks for merging it!

**Comment by wind39** [comment]
Am I getting it wrong, or OpenCV native DLLs being packaged here are only Windows DLLs?

What do I need to do if I want to deliver an application that:
- Uses opencvsharp;
- Runs fine on Linux under Mono;
- I don't need to bother the final user to make they install opencv packages on his Linux machine.

Or in other words, is there a way to package Linux DLLs too?

Thanks in advance!

**Comment by marklam** [comment]
It looks like there's code in NativeMethods.cs to not try to load the Windows libraries on a Unix platform, but I don't know any more than that, sorry.

**Comment by shimat** [comment]
If all OpenCV native Linux libraries (e.g. libopencv_core2411.so) are located at the same directory as the executable file, it should work.
But I don't know about the binary compatibility among the Linux distributions. For example, can a library built by Debian work on Fedora?

**Comment by wind39** [comment]
Yes, a library built by Debian should work on Fedora, if they are on same architecture (32 or 64 bits).

However, it is hard to say if it would work really, because the libopencv_core2411.so file can depend on other libraries ("ldd" on the file show if all dependencies are met).

I have a Debian machine here and the latest OpenCV deb packages installed. I'll try to make it work here. But maybe I'll need to put other libraries (OpenCV dependencies) on the bin folder.

What do you guys think? If another library (other than OpenCV native .so files for Linux) needs to be on the same directory, should we package with opencvsharp?
Maybe we'll need to check the license of this library.. But since it is on Debian repos it should be open source too.

Of course it is only an assumption. By the way, I work with opencvsharp with Mono and OpenCV deb packages installed. But it would be nice if the user wouldn't need to install these packages. I'll try to make it work and I report here, ok?

**Pull request merged**
