### PR TITLE
Update Size.cs

### PR DESCRIPTION
**Pull request by RemyEE**
Make Width and Height as Properties, which can be use for databinding as user wish

### CODE REVIEW

**Comment by sdcb** [comment]
I don't like structure stuff are properties because this would have negative impact of performance

**Comment by shimat** [comment]
I understand both opinions. I am somewhat negative about this change.

As another perspective, "auto properties" are not supposed to be used.
https://stackoverflow.com/questions/28488057/what-is-the-structlayoutattribute-effect-on-properties-in-c

**Comment by hez2010** [comment]
> I don't like structure using properties because this would have negative impact of performance

It's not correct, it will be inlined at JIT time if you're using .NET Core 3.1+, so reading and writing to properties won't impact performance. Despite it I still don't like this change because it may affect the struct layout using auto-property. Instead manual properties should be used if property pattern is preferred.

**Comment by sdcb** [comment]
> It's not correct, it will be inlined at JIT time if you're using .NET Core 3.1+, so reading and writing to properties won't impact performance. Despite I still don't like this change because it may affect the struct layout using auto-property. Instead manual properties should be used if property pattern is preferred.

No, inlining is not happening every time, Debug build won't generally do inlining. This is a so important because we will debug and use the `Size` structure every day, some code like this:
```csharp
for (int row = 0; row < size.Height; ++row)
    for(int col = 0; col < size.Width; ++col)
        // do something...
```
Would have ~300% negative impact on performance only because of the property call.

**Pull request closed without merging**
